development:
  adapter: mysql
  encoding: utf8
  database: bddcodetest_development
  username: root
  password: root
  host: localhost

test: &TEST
  adapter: mysql
  encoding: utf8
  database: bddcodetest_test
  username: root
  password: root
  host: localhost

cucumber:
  <<: *TEST

